# Generated by Django 6.0.5 on 2026-05-06 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motos', to='core.piloto')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('proceso', 'En Proceso'), ('terminado', 'Terminado')], default='pendiente', max_length=20)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='core.moto')),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='core.piloto')),
            ],
        ),
    ]
