# Generated by Django 6.0.5 on 2026-05-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='horas_uso',
            field=models.IntegerField(default=0),
        ),
    ]
