# Generated by Django 6.0.5 on 2026-05-06 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_moto_horas_uso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='fecha_salida',
        ),
        migrations.AddField(
            model_name='servicio',
            name='horas_servicio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo',
            field=models.CharField(choices=[('alistamiento', 'Alistamiento'), ('reparacion', 'Reparación')], default='alistamiento', max_length=20),
        ),
        migrations.CreateModel(
            name='ServicioExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='core.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicio')),
            ],
            options={
                'unique_together': {('servicio', 'item')},
            },
        ),
        migrations.AddField(
            model_name='servicio',
            name='items',
            field=models.ManyToManyField(blank=True, through='core.ServicioItem', to='core.item'),
        ),
    ]
