# Generated by Django 6.0.5 on 2026-05-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_remove_servicio_costo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10),
        ),
    ]
