# Generated by Django 6.0.5 on 2026-05-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='placa',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='piloto',
            name='cc',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
